version: '3.9'
services:
  db:
    image: mysql
    container_name: AnalyserTest
    ports:
      - '3306:3306'
    expose:
      - '3306'
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: example
      MYSQL_DATABASE: AnalyserTest
      
  adminer:
    image: adminer
    container_name: AdminerA
    restart: always
    ports:
      - 8080:8080